### ISSUE TITLE
farfalle

### ISSUE THREAD

**Issue by fenio** [unkn0w/unknownews#1]
Hej,

Nie znalazłem za bardzo info o tym czy w ogóle można zgłaszać propozycje do newsów, a jeżeli tak to jak to robić, więc stwierdziłem, że zrobię to tutaj. Jeśli nie można to zamknij i zapominamy o sprawie ;)

W maju wspominałeś o Perplexica i trochę z tym eksperymentuję, ale rozglądam się po okolicy i od niedawna eksperymentuję też z Farfalle:

https://www.farfalle.dev/
https://github.com/rashadphz/farfalle

Też selfhosted, też wspiera różne modele i lokalne i internetowe.
Możesz wspomnieć o projekcie jak masz ochotę ;)

**Comment by unkn0w** [comment]
Dzięki za polecenie - dorzucę do zestawienia.

Jeśli miałbyś coś jeszcze ciekawego, to możesz dorzucać jako issues 🙂👍

**Comment by fenio** [comment]
Zawsze możesz po znajomości pv-mounter wrzucić ;)
Spoko jak coś ciekawego wynajdę i nie będzie w historii to postaram się wrzucić.
